export const CATEGORIES_GET_CATEGORIES = 'CATEGORIES_GET_CATEGORIES'
export const CATEGORIES_GET_CATEGORIES_POSTS = 'CATEGORIES_GET_CATEGORIES_POSTS'
export const POSTS_GET_POSTS = 'POSTS_GET_POSTS'
export const POSTS_GET_POST = 'POSTS_GET_POSTS'
